apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kubelet-serving-cert-approver.yaml
replacements:
  - source:
      kind: ServiceMonitor
      name: kubelet-serving-cert-approver
      fieldPath: metadata.namespace
    targets:
      - select:
          kind: ServiceMonitor
          name: kubelet-serving-cert-approver
        fieldPaths:
          - spec.namespaceSelector.matchNames.0
