apiVersion: v1
kind: PersistentVolume
metadata:
  name: media
  annotations:
    pv.kubernetes.io/provisioned-by: nfs.csi.k8s.io
spec:
  capacity:
    storage: 8Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi
  mountOptions:
    - vers=3
    - nolock
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: nas-1.southcity.dev#/var/nfs/shared/Media#
    volumeAttributes:
      server: nas-1.southcity.dev
      share: /var/nfs/shared/Media
