apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: homelab-nfs
provisioner: nfs.csi.k8s.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - nfsvers=3
  - nolock
