apiVersion: v1
kind: Secret
metadata:
    name: rivers-sandbox
type: Opaque
stringData:
    AWS_TABLE_URI: ENC[AES256_GCM,data:juDtMN1JZjEVRc8JKWWURyyEy24qAHTY,iv:L6scL+gQhSurU2k4wyJuAfoNZ6NqwWNvagSX+HslbdA=,tag:IkMhkb3Q5MrwKIWf5Bg8GQ==,type:str]
    AWS_ENDPOINT: ENC[AES256_GCM,data:TgEqWZNm7TL/CmpI/6RPdGwf+gBASGDavxnEpeC+2KEqvMo4GJT3aSu3UCy6h30cXJiDz6FnTLawYuJgqU9mNQA=,iv:+hJTP47E2M60VBls2pP3XLGWFQB/rffheuI6mjh9vMI=,tag:LrS17TYASENYgYj/XW9L0A==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:PKjPbMVTSeXlr8lvZdolVW3lhFa9BKOX/hiOhLbFiZo=,iv:GS8+7rfWbjikc/7ZgLHRe3LoWrEmFwyGCqmhUJ/eYOo=,tag:0gBMiwrDONOZwNVUYN4Zfg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Sqm56CVwVJSp+SQ0Eiydiz/r/+AHiQJoR8xOsQeO/eSMX24Lo0HpLltk7VQOpf9DNEqnVsZB4XELK1gIZ9IffQ==,iv:fbTWwQGsvmmIgSJ95ZBxlbnifoab+xhqmgYm25922bA=,tag:Dt1xCyE75dW05pvUEAGESA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3KzgyVlF4b2M4RXhtam1E
            WSt3YkwrK0ZxWWtSZ1ZJS25HQ3hwODdBMVUwCmNndm9KZExnN0VIVmVaTWxkWm0w
            Z3FUUnVtSi9CL1ozZFhqN3ZDTUh0czQKLS0tIGVGbDNuL2ZFakZ3N213WkVIYUxJ
            NkhVS1FPdFRMRFdMcnBJQzdmTDYzaEUKwMWww0nYdolL6aqcIoL8rN2XfIc6JOln
            jg5/Y191tAQI0NxxvkBL9FZ4RXStivBQd27dNfOpWmVWgIeqnggPcg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1txmpc45rsl3yg5hk5wkrkcwtvlqn8mx5n7q70nel5ggjnwd2ygvquggdx3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-15T18:07:45Z"
    mac: ENC[AES256_GCM,data:GRJjJiyL+cgCI7mkpkyckOoEvogXenvPZZqJGn8fqq/zVhuJFUJfNMFNARu9SRjpfLAy3cjXfXy/GqlMIctNh9YiMJbQme1qNCbJz8QQ4dCWgorFNmR2IjjLbPqtTVCs0W/fhM3zmL1S0xA7sg57E/uNVX1QkrkKiRgAQwP11aw=,iv:qf9rvKf1ATm1nXYZyEJ0hUuAqgpatDwcD+z4uoq77+s=,tag:e23nrsUzmqY5rx1pEaFjuA==,type:str]
    version: 3.13.1
