apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: []
configMapGenerator:
  - name: longhorn-grafana-dashboards
    files:
      - ./dashboards/longhorn.json
    options:
      labels:
        grafana_dashboard: "1"
        app.kubernetes.io/part-of: longhorn
        app.kubernetes.io/component: monitoring
