apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: keycloak
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: Keycloak
    gethomepage.dev/description: Identity and Access Management
    gethomepage.dev/group: Cluster
    gethomepage.dev/icon: keycloak.png
    gethomepage.dev/pod-selector: "app.kubernetes.io/instance=keycloak"
spec:
  parentRefs:
    - name: http
      namespace: kgateway
  hostnames:
    - keycloak.${CLUSTER_DOMAIN}
  rules:
    - backendRefs:
        - name: keycloak-service
          port: 8080
