apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: metallb
spec:
  interval: 1h
  serviceAccountName: flux
  url: oci://ghcr.io/ssouthcity/mirror/charts/metallb
  ref:
    semver: ~0
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: extract
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
spec:
  releaseName: metallb
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: metallb
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    prometheus:
      serviceMonitor:
        enabled: true
