apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: metallb
spec:
  interval: 1h
  serviceAccountName: flux
  url: oci://ghcr.io/ssouthcity/mirror/charts/metallb
  ref:
    tag: 0.16.1 # {"$imagepolicy": "updates-infra:metallb:tag"}
    digest: sha256:fce8488843290973447cc7a2f74bb00eec4573a63f9f84141b0cfd5ac4b1629a # {"$imagepolicy": "updates-infra:metallb:digest"}
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: extract
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: metallb
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    prometheus:
      rbacPrometheus: false
      serviceMonitor:
        enabled: true
