apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: descheduler
spec:
  interval: 1h
  serviceAccountName: flux
  url: oci://ghcr.io/ssouthcity/mirror/charts/descheduler
  ref:
    tag: 0.35.1 # {"$imagepolicy": "updates-infra:descheduler:tag"}
    digest: sha256:c7a26ed82193944d8e7b56a5bdc0073134aa1e6d8cdabb457f854aae92e54721 # {"$imagepolicy": "updates-infra:descheduler:digest"}
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: extract
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: descheduler
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: descheduler
  driftDetection:
    mode: enabled
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    kind: Deployment
    service:
      enabled: true
    serviceMonitor:
      enabled: true
