apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: rivers
spec:
  interval: 1h
  serviceAccountName: flux
  url: oci://ghcr.io/ion-elgreco/charts/rivers
  ref:
    semver: 0.1.4
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: extract
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rivers
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: rivers
  driftDetection:
    mode: enabled
  values: {}
