apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: rivers-crds
spec:
  interval: 1h
  serviceAccountName: flux
  url: oci://ghcr.io/ion-elgreco/charts/rivers-crds
  ref:
    tag: 0.3.0 # {"$imagepolicy": "updates-infra:rivers-crds:tag"}
    digest: sha256:03f7a1d811ab717cf4cff7ef25c1f9b028f37de27b58d1d8779be7473392e42a # {"$imagepolicy": "updates-infra:rivers-crds:digest"}
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: extract
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rivers-crds
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: rivers-crds
  driftDetection:
    mode: enabled
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values: {}
