apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: rivers-crds
spec:
  interval: 1h
  serviceAccountName: flux
  url: oci://ghcr.io/ion-elgreco/charts/rivers-crds
  ref:
    tag: 0.2.0 # {"$imagepolicy": "updates-apps:rivers-crds:tag"}
    digest: sha256:d7749e65843b641e0ce9b247c555fbabd86d667e5a4fe9a5d75387bcbac65950 # {"$imagepolicy": "updates-apps:rivers-crds:digest"}
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: extract
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rivers-crds
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: rivers-crds
  driftDetection:
    mode: enabled
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values: {}
