apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: rivers
spec:
  interval: 1h
  serviceAccountName: flux
  url: oci://ghcr.io/ion-elgreco/charts/rivers
  ref:
    semver: 0.2.1
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: extract
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rivers
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: rivers
  driftDetection:
    mode: enabled
  values:
    ui:
      httpRoute:
        enabled: true
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Rivers
          gethomepage.dev/description: Asset Orchestration
          gethomepage.dev/group: Data Engineering
          gethomepage.dev/icon: https://raw.githubusercontent.com/ion-elgreco/rivers/refs/heads/main/assets/logo.svg
          gethomepage.dev/pod-selector: "app.kubernetes.io/instance=rivers"
        parentRefs:
          - name: http
            namespace: kgateway
        hostnames:
          - rivers.${CLUSTER_DOMAIN}
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: surrealdb
            patch: |-
              - op: add
                path: /spec/template/spec/securityContext
                value:
                  fsGroup: 1000
                  runAsUser: 1000
                  runAsGroup: 1000
          - target:
              kind: Role
              name: rivers-executor
            patch: |-
              - op: replace
                path: /rules/1/verbs
                value: ["get", "list", "watch", "create", "update", "patch", "delete"]
