apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: longhorn
spec:
  interval: 1h
  serviceAccountName: flux
  url: oci://ghcr.io/ssouthcity/mirror/charts/longhorn
  ref:
    tag: 1.12.1 # {"$imagepolicy": "updates-infra:longhorn:tag"}
    digest: sha256:fa0442c0f42d8e557a90cd591b583448160679ef9c72b6ff9d3eaa14a8b365f0 # {"$imagepolicy": "updates-infra:longhorn:digest"}
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: extract
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: longhorn
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    defaultSettings:
      allowCollectingLonghornUsageMetrics: false
    httproute:
      enabled: true
      annotations:
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: Longhorn
        gethomepage.dev/description: Distributed Block Storage
        gethomepage.dev/group: Cluster
        gethomepage.dev/icon: longhorn.png
        gethomepage.dev/pod-selector: ""
      parentRefs:
        - name: http
          namespace: kgateway
      hostnames:
        - "longhorn.${CLUSTER_DOMAIN}"
    metrics:
      serviceMonitor:
        enabled: true
