apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:oSIl6vsvMpKI0WfVHtw4OqHLq2FNYsGGrroYQuXxWf7fRBSTmGkcWVhkrM8bwkc/Ek+nA3w=,iv:bdi3ampPMrb4O/sKQVoqK+B+NZko0Wx7/egAfUiFvfs=,tag:Fn1C2VXwcWnpZVF0sW+LfQ==,type:str]
sops:
    age:
        - recipient: age1txmpc45rsl3yg5hk5wkrkcwtvlqn8mx5n7q70nel5ggjnwd2ygvquggdx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4TnB3elJtck9oU3d0dmlF
            VnRYc040TTRCNHk2SlZVNUN6UFZrVE03ODI0Cm9QcmtCTERtb1hRSW5SblhRQmxv
            T3ZsZnV4M3J3a3BWL3BVUnFHNzByVWsKLS0tIG9Dckd3TnZaV3JhTlBtbHVVSzY1
            cjduL3IrTjJ0Q0RwR3dNb2hNMGFmZzAKURrcYGVzZQeNjgpDVL90bbACINj9dxNo
            E/2dOEUhoSkDIlkf+BvXFNujHHEDbd2WHNKQPD81lCbUCMgFWhT5GA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-22T22:09:58Z"
    mac: ENC[AES256_GCM,data:co0nSmBPb4aLD3f/QlQcpQ8wMQ2RGaU08YTuc/VlQ1OnxPIB3CfOFC+sXDm7KYpsKxL0TiuRPl/ENbOfHvRmVubUf5Pj4hKK6vQAsgyV+rCQfOVKX9qj0Qs2a/D+4QZ3ecrQk7CN09TeF4dh9g+tPtzy17NxTEJ+GWCOhMKf1Eg=,iv:PPt164XJwS3/h6h+bOhMDj7OFvafhwDTOBFP2rNUQPQ=,tag:sQBOW7t9dk/8VcEt2mnltg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
