apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: cert-manager
spec:
  provider: generic
  serviceAccountName: flux
  image: ghcr.io/ssouthcity/mirror/charts/cert-manager
  interval: 12h
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: cert-manager
spec:
  imageRepositoryRef:
    name: cert-manager
  policy:
    semver:
      range: ">=1.20.2"
  digestReflectionPolicy: IfNotPresent
