apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: cloudnative-pg
spec:
  provider: generic
  image: ghcr.io/cloudnative-pg/charts/cloudnative-pg
  interval: 12h
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: cloudnative-pg
spec:
  imageRepositoryRef:
    name: cloudnative-pg
  policy:
    semver:
      range: ">=0.28.3"
  digestReflectionPolicy: IfNotPresent
