apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: external-dns
spec:
  provider: generic
  serviceAccountName: flux
  image: ghcr.io/ssouthcity/mirror/charts/external-dns
  interval: 12h
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: external-dns
spec:
  imageRepositoryRef:
    name: external-dns
  policy:
    semver:
      range: ">=1.21.1"
  digestReflectionPolicy: IfNotPresent
