apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: kgateway
spec:
  provider: generic
  serviceAccountName: flux
  image: cr.kgateway.dev/kgateway-dev/charts/kgateway
  interval: 12h
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: kgateway
spec:
  imageRepositoryRef:
    name: kgateway
  policy:
    semver:
      range: ">=2.3.4"
  digestReflectionPolicy: IfNotPresent
