apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: longhorn
spec:
  provider: generic
  image: ghcr.io/ssouthcity/mirror/charts/longhorn
  interval: 12h
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: longhorn
spec:
  imageRepositoryRef:
    name: longhorn
  policy:
    semver:
      range: ">=1.12.0"
  digestReflectionPolicy: IfNotPresent
