apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: metallb
spec:
  provider: generic
  serviceAccountName: flux
  image: ghcr.io/ssouthcity/mirror/charts/metallb
  interval: 12h
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: metallb
spec:
  imageRepositoryRef:
    name: metallb
  policy:
    semver:
      range: ">=0.16.1"
  digestReflectionPolicy: IfNotPresent
