apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: rivers-crds
spec:
  provider: generic
  image: ghcr.io/ion-elgreco/charts/rivers-crds
  interval: 12h
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: rivers-crds
spec:
  imageRepositoryRef:
    name: rivers-crds
  policy:
    semver:
      range: ">=0.2.1"
  digestReflectionPolicy: IfNotPresent
