apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:rfu2enMPobS7DarVffqJ6/viq70hY9HtpHrKYjxJz1hE2Uj7iIBt6gtnO5fpaue5XuexsZo=,iv:gLxAEHL66BcxqUb2SpK64AmJn0JX54cAsWTKiry3S/o=,tag:8Zm+oGzKIzBRQ8dm3Mi1Gw==,type:str]
sops:
    age:
        - recipient: age1txmpc45rsl3yg5hk5wkrkcwtvlqn8mx5n7q70nel5ggjnwd2ygvquggdx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpWWk4SkRVaEVJc1VOamJJ
            NFZ4Ykc0WUJJK2JoVWoxbFE5cVI2VzZvRWlJCmhJdGlOMjEvUDg5cHNKcUgxanRU
            NUdnWHltSERsSXo4WkxsS2tZdUtmZ2MKLS0tIGhDYWVobmUzTHdVQmZGeEZJVDBj
            NjlSaUx5aW1DUURhYVN2b0o0cnJUSWcKyAWa7yhY428Xt+igPSN3vlnajJ+076ft
            a65lcfrkvVHWC70oNOSrANZm9qMMDzMS9T7hEBC+1YccyxHq3PbIPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-23T00:02:39Z"
    mac: ENC[AES256_GCM,data:igZIKhTWJvApZfc6NosGGKF2zSmeQySc6zfJekJn308p/BBoApKlv78hCujgB1GG2hvTBf2erlUteEozUS6w+ncXUCwvkFbRvfXmmeVo/xgX0eI2gx7a8vw9JubNuyKJEO697iBm3bNge3Q9z7r7xFh7SOrUs8/QeBvp/tMccM8=,iv:w0UQYmg1cesnT6Dv01NLhDKDD/3J2ziD0/gK/zSs17A=,tag:ZDIRaQJYhSIgRtt953uxuw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
