apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ipaddresspool.yaml
  - ./l2advertisement.yaml
configMapGenerator:
  - name: metallb-grafana-dashboards
    files:
      - ./dashboards/metallb.json
    options:
      labels:
        grafana_dashboard: "1"
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: monitoring
