apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: metrics-server
spec:
  interval: 1h
  url: oci://ghcr.io/controlplaneio-fluxcd/charts/metrics-server
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  ref:
    tag: 3.13.1 # {"$imagepolicy": "updates-infra:metrics-server:tag"}
    digest: sha256:13b20bd63b807f851a4f131a6c2af20741a8450d81876467b9cf67de5b9a4bf5 # {"$imagepolicy": "updates-infra:metrics-server:digest"}
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
spec:
  serviceAccountName: flux
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: metrics-server
