apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: metrics-server
spec:
  interval: 1h
  url: oci://ghcr.io/controlplaneio-fluxcd/charts/metrics-server
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  ref:
    tag: 3.14.0 # {"$imagepolicy": "updates-infra:metrics-server:tag"}
    digest: sha256:9706c788cdb59b128c0fcd68711921cbdd516c9a48d7bd13993facbd932d205c # {"$imagepolicy": "updates-infra:metrics-server:digest"}
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
spec:
  serviceAccountName: flux
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: metrics-server
