apiVersion: mirror.fluxcd.io/v1alpha1
kind: Config
charts:
  - name: external-dns
    source: https://kubernetes-sigs.github.io/external-dns/
    destination: oci://ghcr.io/ssouthcity/mirror/charts
    limit: 3
