apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: cloudnative-pg
spec:
  interval: 1h
  url: oci://ghcr.io/cloudnative-pg/charts/cloudnative-pg
  ref:
    tag: 0.28.3 # {"$imagepolicy": "updates-infra:cloudnative-pg:tag"}
    digest: sha256:e01684efd9aa83c81578a2f624c0bd702e607844b8f0bf19196230322703485a # {"$imagepolicy": "updates-infra:cloudnative-pg:digest"}
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: extract
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: cloudnative-pg
  driftDetection:
    mode: enabled
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    monitoring:
      podMonitorEnabled: true
