apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./rbac.yaml
configMapGenerator:
  - name: cloudnative-pg-grafana-dashboards
    files:
      - ./dashboards/cloudnative-pg.json
    options:
      labels:
        grafana_dashboard: "1"
        app.kubernetes.io/part-of: cloudnative-pg
        app.kubernetes.io/component: monitoring
