apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "homepage.fullname" . }}
  labels:
    {{- include "homepage.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: |
    {{- tpl $value $ | nindent 4 }}
  {{- end }}
