apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: []
configMapGenerator:
  - name: external-dns-grafana-dashboards
    files:
      - ./dashboards/external-dns.json
    options:
      labels:
        grafana_dashboard: "1"
        app.kubernetes.io/part-of: external-dns
        app.kubernetes.io/component: monitoring
