apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: homepage
spec:
  interval: 1h
  serviceAccountName: flux
  url: oci://ghcr.io/ssouthcity/charts/homepage
  ref:
    semver: ~0
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: extract
  verify:
    provider: cosign
    matchOIDCIdentity:
      - issuer: ^https://token\.actions\.githubusercontent\.com$
        subject: ^https://github\.com/ssouthcity/homelab-infra/\.github/workflows/publish-charts\.yaml@refs/heads/main$
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: homepage
  values:
    httpRoute:
      enabled: true
      annotations:
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: Homepage
        gethomepage.dev/description: Dynamically Detected Homepage
        gethomepage.dev/group: Discoverability
        gethomepage.dev/icon: homepage.png
        gethomepage.dev/pod-selector: ""
      parentRefs:
        - name: http
          namespace: kgateway
      hostnames:
        - "homepage.${CLUSTER_DOMAIN}"
    config:
      kubernetes.yaml: |
        mode: cluster
        ingress: false
        traefik: false
        gateway: true
      widgets.yaml: |
        - kubernetes:
            cluster:
              show: true
              cpu: true
              memory: true
              showLabel: true
              label: "cluster"
            nodes:
              show: true
              cpu: true
              memory: true
              showLabel: true
        - resources:
            backend: resources
            expanded: true
            cpu: true
            memory: true
            network: default
        - search:
            provider: duckduckgo
            target: _blank
      bookmarks.yaml: |
        - Developer:
            - Github:
                - abbr: GH
                  href: https://github.com/
