apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kgateway
spec:
  interval: 1h
  url: oci://cr.kgateway.dev/kgateway-dev/charts/kgateway
  ref:
    tag: v2.4.1 # {"$imagepolicy": "updates-infra:kgateway:tag"}
    digest: sha256:0506dbe67a5d83db6044783cba59de00d295de6ff0cb179bde62dd7ac7e9466f # {"$imagepolicy": "updates-infra:kgateway:digest"}
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kgateway
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: kgateway
  driftDetection:
    mode: enabled
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    controller:
      serviceMonitor:
        enabled: true
