apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kgateway-crds
spec:
  interval: 1h
  url: oci://cr.kgateway.dev/kgateway-dev/charts/kgateway-crds
  ref:
    tag: v2.3.5 # {"$imagepolicy": "updates-infra:kgateway-crds:tag"}
    digest: sha256:79dd587a2462bff12fe64711a0532e3b73e4c2a1376e0a7ec47714117aa89152 # {"$imagepolicy": "updates-infra:kgateway-crds:digest"}
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kgateway-crds
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: kgateway-crds
  driftDetection:
    mode: enabled
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
