apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kgateway
spec:
  interval: 1h
  url: oci://cr.kgateway.dev/kgateway-dev/charts/kgateway
  ref:
    tag: v2.4.2 # {"$imagepolicy": "updates-infra:kgateway:tag"}
    digest: sha256:a459de853c13fe144aade84d2cb3c7572dc463f4de8689e475c9691adf1c202b # {"$imagepolicy": "updates-infra:kgateway:digest"}
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kgateway
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: kgateway
  driftDetection:
    mode: enabled
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    controller:
      serviceMonitor:
        enabled: true
