apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kgateway
spec:
  interval: 1h
  url: oci://cr.kgateway.dev/kgateway-dev/charts/kgateway
  ref:
    tag: v2.4.3 # {"$imagepolicy": "updates-infra:kgateway:tag"}
    digest: sha256:b7e3da3048b638c02a520ecd2b37bce176745ccf6f98fbd3d33a88df3d6cca4c # {"$imagepolicy": "updates-infra:kgateway:digest"}
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kgateway
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: kgateway
  driftDetection:
    mode: enabled
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    controller:
      serviceMonitor:
        enabled: true
