apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kgateway-crds
spec:
  interval: 1h
  url: oci://cr.kgateway.dev/kgateway-dev/charts/kgateway-crds
  ref:
    tag: v2.4.6 # {"$imagepolicy": "updates-infra:kgateway-crds:tag"}
    digest: sha256:9308e5fb6608838b44e66b42ea44782082b952bcea873f49f9b63ae117b10abf # {"$imagepolicy": "updates-infra:kgateway-crds:digest"}
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kgateway-crds
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: kgateway-crds
  driftDetection:
    mode: enabled
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
