name: mirror-charts
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        component:
          - cert-manager
          - descheduler
          - external-dns
          - longhorn
          - metallb
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Flux Mirror CLI
        uses: fluxcd/flux-mirror/actions/setup@030f59c128efe9d42b00a4242a1fd1d401dbd3e0 # v0.7.0
      - name: Login to Github Container Registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Sync Kubernetes SIGs Charts
        run: flux-mirror sync sync/$COMPONENT.yaml --no-progress
        env:
          COMPONENT: ${{ matrix.component }}
