name: mirror-charts
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        component:
          - cert-manager
          - descheduler
          - external-dns
          - longhorn
          - metallb
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Setup Flux Mirror CLI
        uses: fluxcd/flux-mirror/actions/setup@030f59c128efe9d42b00a4242a1fd1d401dbd3e0 # v0.7.0
      - name: Login to Github Container Registry
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Sync Kubernetes SIGs Charts
        run: flux-mirror sync sync/$COMPONENT.yaml --no-progress
        env:
          COMPONENT: ${{ matrix.component }}
