name: Publish Helm Charts

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - charts/**

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      matrix:
        chart:
          - homepage
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Helm
        uses: azure/setup-helm@dda3372f752e03dde6b3237bc9431cdc2f7a02a2 # v5.0.0
      - name: Setup Cosign
        uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6 # v4.1.2
      - name: Login to Github Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Package Chart
        run: |
          helm package charts/${{ matrix.chart }}
      - name: Publish Chart
        id: publish
        run: |
          helm push \
            ${{ matrix.chart }}-*.tgz \
            oci://ghcr.io/${{ github.repository_owner }}/charts \
            &> push-metadata.txt
          CHART_DIGEST=$(awk '/Digest: /{print $2}' push-metadata.txt)
          echo "digest=${CHART_DIGEST}" | tee -a $GITHUB_OUTPUT
      - name: Sign Chart
        run: |
          cosign sign --yes ghcr.io/${{ github.repository_owner }}/charts/${{ matrix.chart }}:${{ steps.publish.outputs.digest }}
      - name: Verify Signature
        run: |
          cosign verify "ghcr.io/${{ github.repository_owner }}/charts/${{ matrix.chart }}@${{ steps.publish.outputs.digest }}" \
            --certificate-oidc-issuer "https://token.actions.githubusercontent.com" \
            --certificate-identity "https://github.com/${GITHUB_WORKFLOW_REF}"
