name: push-artifact

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - components/**

jobs:
  push-artifact:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        component:
          - cert-manager
          - cloudnative-pg
          - csi-nfs
          - external-dns
          - gateway-api
          - homepage
          - keycloak
          - kgateway
          - kubelet-serving-cert-approver
          - longhorn
          - metallb
          - monitoring
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Flux CLI
        uses: controlplaneio-fluxcd/distribution/actions/setup@edec676143e5cc5010e5b7dccd998cbd9dcd1b90 # v2.8.7
      - name: Setup Cosign
        uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6 # v4.1.2
      - name: Login to Github Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push artifact
        uses: controlplaneio-fluxcd/distribution/actions/push@edec676143e5cc5010e5b7dccd998cbd9dcd1b90 # v2.8.7
        id: push
        with:
          repository: ghcr.io/${{ github.repository }}/${{ matrix.component }}
          path: "./components/${{ matrix.component }}"
          diff-tag: latest
      - name: Sign artifact
        if: steps.push.outputs.pushed == 'true'
        run: cosign sign --yes $DIGEST_URL
        env:
          DIGEST_URL: ${{ steps.push.outputs.digest-url }}
